leashing:
  villager: true
  wandering_trader: true
  zombie_villager: false
names:
  first:
  - Aaliyah
  - Aary
  - Abigail
  - Adalyn
  - Aiden
  - Akrat
  - Alexander
  - Amelia
  - Aria
  - Ariana
  - Asher
  - Aubrey
  - Aurora
  - Ava
  - Avery
  - Baka
  - Barry
  - Benjamin
  - Berry
  - Billzo
  - Birch
  - Blackberry
  - Blueberry
  - Blunt
  - Bovine
  - Buwa
  - Caden
  - Caleb
  - Cameron
  - Camilla
  - Carson
  - Carter
  - Cary
  - Chambi
  - Charlie
  - Charlotte
  - Chloe
  - Chris
  - Chunk
  - Cocanine
  - Colton
  - Cranberry
  - Dairy
  - Daniel
  - Diamond
  - Earring
  - Elena
  - Eliana
  - Elijah
  - Ella
  - Ellie
  - Emerald
  - Emilia
  - Emily
  - Emma
  - Espion
  - Ethan
  - Evelyn
  - Everly
  - Ezra
  - Fairy
  - Ferry
  - Fynch
  - Gabriel
  - Gary
  - Gerry
  - Glory
  - Goldie
  - Grayson
  - Hairy
  - Hannah
  - Harper
  - Harry
  - Henry
  - Holden
  - Honag
  - Hrrm
  - Hurrm
  - Hurrrm
  - Isaac
  - Isabella
  - Isaiah
  - Isla
  - Jack
  - Jackie
  - Jackson
  - Jakob
  - James
  - Jasper
  - Jayce
  - Jayden
  - Jerry
  - Joe
  - Julian
  - Karen
  - Keri
  - Kinsley
  - Larry
  - Layla
  - Lazy
  - Leah
  - Leo
  - Levy
  - Liam
  - Lila
  - Lily
  - Lincoln
  - Logan
  - Lucas
  - Luna
  - Madelyn
  - Madison
  - Mary
  - Mason
  - Matteo
  - Matthew
  - Maverick
  - Maya
  - Merry
  - Mia
  - Michael
  - Mila
  - Miles
  - Muhammad
  - Netherite
  - Noah
  - Nora
  - Nova
  - Nugget
  - Oliver
  - Olivia
  - Owen
  - Owosome
  - Paisley
  - Parry
  - Penelope
  - Quartz
  - Raspberry
  - Rat
  - Riley
  - Ryan
  - Samuel
  - Sarah
  - Sarmii
  - Scarlett
  - Sebastian
  - Sherry
  - Smith
  - Sniki
  - Sophia
  - Sorry
  - Suwa
  - Terry
  - Toby
  - Vikkeur
  - Vlad
  - Walrus
  - Wary
  - Weedy
  - William
  - Wyatt
  - Yakson
  - Yeti
  - Yumsome
  - Zoe
  last:
  - Aardvark
  - Bakalarachi
  - Baron
  - Bass
  - Bee
  - Blunt
  - Bovine
  - Candycane
  - Caterpillar
  - Chess
  - Christ
  - Class
  - Claus
  - Cube
  - Death
  - Drugglez
  - Duck
  - Dukk
  - Ekto
  - Ektobawaeur
  - Garfield
  - Gas
  - Goldfish
  - Golem
  - Heksagon
  - Hexagon
  - Hmm
  - Hrm
  - Hurm
  - Inbred
  - Ingot
  - Ironforests
  - Jackass
  - Jasperlandtwo
  - Larachi
  - Mass
  - Matteoville
  - Moolah
  - Nervegas
  - Newrhodes
  - Nuke
  - Oolah
  - Oolahist
  - Owo
  - Pie
  - Plutonium
  - Pompeii
  - Porkchop
  - Poutine
  - Puzic
  - RandumPerson314
  - Rozman
  - Rubik
  - Sandals
  - Sexagon
  - Sheppard
  - Smith
  - Snikigung
  - Snowman
  - Staline
  - Sugar
  - Thorium
  - Tobytopia
  - Toothbrush
  - Trespass
  - Uranium
  - Wambi
  - Weeeeed
  - Woveyad
  - Yeti