leashing:
  villager: true
  wandering_trader: true
  zombie_villager: false
names:
  first:
  - Aaliyah
  - Aary
  - Abigail
  - Adalyn
  - Aiden
  - Alexander
  - Amelia
  - Aria
  - Ariana
  - Asher
  - Aubrey
  - Aurora
  - Ava
  - Avery
  - Barry
  - Benjamin
  - Berry
  - Billzo
  - Birch
  - Blackberry
  - Blackcherry
  - Blueberry
  - Blunt
  - Bovine
  - Caden
  - Caleb
  - Cameron
  - Camilla
  - Carry
  - Carson
  - Carter
  - Cary
  - Charlie
  - Charlotte
  - Chloe
  - Chris
  - Chunk
  - Cocaniny
  - Colton
  - Cranberry
  - Dairy
  - Daniel
  - Druggie
  - Earring
  - Elena
  - Eliana
  - Elijah
  - Ella
  - Ellie
  - Emilia
  - Emily
  - Emma
  - Ethan
  - Evelyn
  - Everly
  - Ezra
  - Fairy
  - Ferry
  - Fynchy
  - Gabriel
  - Gary
  - Gerry
  - Gianna
  - Glary
  - Glory
  - Goldie
  - Googly
  - Grayson
  - Hairy
  - Hannah
  - Harper
  - Harry
  - Henry
  - Holdy
  - Hrrm
  - Hurrm
  - Hurrrm
  - Isaac
  - Isabella
  - Isaiah
  - Isla
  - Jack
  - Jackie
  - Jackson
  - Jakob
  - James
  - Jasper
  - Jayce
  - Jayden
  - Jerry
  - Josiah
  - Julian
  - Karen
  - Kerosene
  - Kinsley
  - Laim
  - Larry
  - Layla
  - Lazy
  - Leah
  - Leo
  - Levi
  - Liam
  - Lila
  - Lily
  - Lincoln
  - Logan
  - Luca
  - Lucas
  - Luke
  - Luna
  - Madelyn
  - Madison
  - Mary
  - Mason
  - Matteo
  - Matthew
  - Maverick
  - Maya
  - Merry
  - Mia
  - Michael
  - Mila
  - Miles
  - Most popular baby names of 2020
  - Muhammad
  - Noah
  - Nora
  - Nova
  - Oliver
  - Olivia
  - Owen
  - Paisley
  - Parry
  - Penelope
  - Peyton
  - Quantum
  - Quarry
  - Raspberry
  - Riley
  - Ryan
  - Samuel
  - Sarah
  - Scarlett
  - Scary
  - Sebastian
  - Sherry
  - Smith
  - Sophia
  - Sorry
  - Terry
  - Toby
  - Very
  - Walrus
  - Wary
  - Weedy
  - William
  - Wyatt
  - Yakson
  - Yeti
  - Zoe
  last:
  - Aardvark
  - Ass
  - Baron
  - Bass
  - Bee
  - Biden
  - Blunt
  - Bluntson
  - Bovine
  - Bypass
  - Candycane
  - Caterpillar
  - Christ
  - Class
  - Claus
  - Crass
  - Cube
  - Death
  - Dragonson
  - Druggledealerson
  - Duck
  - Elchapo
  - Garfield
  - Gas
  - Goldfish
  - Golem
  - Grass
  - H'mm
  - Herrm
  - Hexagon
  - Hm
  - Hmm
  - Hmmm
  - Holden
  - Honag
  - Hrm
  - Hrrm
  - Hrrrm
  - Hrrrmson
  - Hurm
  - Hurrm
  - Hurrrm
  - Inbred
  - Ingot
  - Ironforests
  - Jackass
  - Jakob
  - Jasper
  - Jasperlandtwo
  - Liam
  - Mass
  - Matteoville
  - Moolah
  - Nervegas
  - Netherite
  - Newrhodes
  - Nuke
  - Ohio
  - Pass
  - Pie
  - Plutonium
  - Pompeii
  - Porkchop
  - Puzic
  - RandumPerson314
  - Rubik
  - Sandals
  - Sheppard
  - Smith
  - Snowman
  - Stolen
  - Thorium
  - Tobytopia
  - Toothbrush
  - Trespass
  - Trump
  - Trumpet
  - Uranium
  - Weeeeed
  - Yeti
  - Youtubson